name: clanz
description: 4CG Clanz App

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/4cg-icon.png
