name: clanz
description: 4CG Clanz App

dependencies:
  flutter:
    sdk: flutter
  get: ^2.14.1
  cloud_functions: ^0.5.0
  firebase_messaging: ^6.0.16
  provider: ^4.1.3
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  get_it: ^4.0.2
  rflutter_alert: ^1.0.3
  flutter_icons: ^1.1.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/4cg-icon.png
  uses-material-design: true
  fonts:
    - family:  CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
